name: Deploy Baseimage

# Will only run on pushes to the docker directory, to prevent a rebuild of the base image on every change.
# We also only build on develop, so that the latest base image is always valid. If you want to verify with  an snapshot image, please push one
# to your local registry and build from there.

on:
  push:
    paths:
      - docker/**
  workflow_dispatch:

env:
  IMAGE_NAME: fiware/orion-ld-base
  IMAGE_TAG: latest

jobs:
  deploy-quay:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }}
          dockerfiles: |
            ./docker/Dockerfile-ubi-base

      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

  deploy-dockerhub:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          file: docker/Dockerfile-ubi-base