name: Compliance Test

on:
  pull_request:

jobs:
  compliance:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Test
        run: |
          $(pwd)/docker/build.sh -s compliance -t -p  $(pwd)
