name: Deploy pre temporal image

on:
  push:
#    branches:
#      - feature/temporal

env:
  IMAGE_NAME: fiware/orion-ld
  IMAGE_TAG_PRE: 0.6-TEMPORAL-PRE-${{ github.run_number }}

jobs:
  deploy-release:

    runs-on: ubuntu-18.04
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_PRE }}
          file: docker/Dockerfile