name: Test compatiblity to mintaka

on:
  push:

jobs:
  test-latest:
    runs-on: ubuntu-18.04

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Build and push to local registry
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker/Dockerfile-ubi
          tags:  localhost:5000/orion-ld:latest

      - uses: actions/checkout@v2
        with:
          repository: fiware/mintaka

      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk

      - name: Run tests
        run: mvn clean test
        env:
          ORION_IMAGE: localhost:5000/orion-ld:latest