name: Static code analysis

on:
  push:

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: cppcheck
        uses: deep5050/cppcheck-action@v3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          inline_suppression: enable

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: cppcheck-report
          path: ./cppcheck_report.txt