name: Valgrind check

on:
  schedule:
    # every night at one
    - cron: '0 1 * * *'
  # or on a manual trigger
  workflow_dispatch:

jobs:
  valgrind-suite:
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        testIndexToStartAt: [0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400, 1500]
    steps:

      - uses: actions/checkout@v2

      - name: Execute valgrind
        run: |
          ./test/valgrind/valgrindTestSuite.sh -fromIx ${{ matrix.testIndexToStartAt }} -toIx ${{ matrix.testIndexToStartAt }}+99
